#!/bin/bash

# get absolute path of the dotfiles repo
SCRIPT_DIR=$(echo $(cd $(dirname $0); pwd))


function link_file {
    local file=$1
    local name=`basename $file| sed s/.symlink//`

    ln -svf $file $HOME/.$name
}


function link_all {
    for file in `find $SCRIPT_DIR -name "*.symlink"`
    do
        link_file $file
    done
}


link_all
