#!/bin/bash

# get absolute path of the dotfiles repo
DOTFILES=$(echo $(cd $(dirname $0); pwd))

# setup bash:
rm -f ${HOME}/.bash_profile
rm -f ${HOME}/.bashrc
rm -f ${HOME}/.profile

ln -s ${DOTFILES}/bash/bash_profile ${HOME}/.bash_profile

# setup zsh:
rm -f ${HOME}/.zshenv
rm -f ${HOME}/.zprofile
rm -f ${HOME}/.zshrc
rm -f ${HOME}/.zlogin
rm -f ${HOME}/.zlogout

ln -s ${DOTFILES}/zsh/zshrc ${HOME}/.zshrc
