# ~/.zshrc used regardless of whether this is a login session or not

export DOTFILES="${HOME}/dotfiles"

## generic shell customizations:
. ${DOTFILES}/sh/rc

## enable new style completion
autoload -Uz compinit && compinit

## prompt
export PS1="%F{green}${USER}%F{cyan}@%F{green}%m %F{cyan}%4~ $%F{white} "

# zsh specific aliases
alias srcz="source ${HOME}/.zshrc"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('${HOME}/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "${HOME}/miniconda3/etc/profile.d/conda.sh" ]; then
        . "${HOME}/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="${HOME}/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

